Repository moderntribe/square-one, pull requests merged in 2021-11, with the labels that each got.

#879 Feature/composer v2
  .github/workflows/ci.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  .github/workflows/phpcs.yml
  changelog.md
  composer.json
  composer.lock
  dev/docker/docker-compose.yml
  wp-config-environment.php
Labels: code review

#878 Feature/block editor sliders
  changelog.md
  local-config-sample.php
  wp-content/plugins/core/src/Assets/Theme/JS_Config.php
  wp-content/themes/core/assets/js/src/admin/editor/components.js
  wp-content/themes/core/assets/js/src/admin/editor/preview.js
  wp-content/themes/core/assets/js/src/theme/config/wp-settings.js
  wp-content/themes/core/assets/js/src/utils/tests.js
  wp-content/themes/core/components/blocks/_css/block-editor.pcss
  wp-content/themes/core/components/slider/js/slider.js
Labels: code review, merge

#873 Support react apps in dev mode
  package.json
  webpack/configs/app-base.js
  webpack/example.js
  webpack/rules/styles.js
  wp-content/plugins/core/src/Assets/Theme/Scripts.php
  yarn.lock
Labels: merge
