Repository moderntribe/square-one, pull requests merged in 2021-12, with the labels that each got.

#773 Can't make this a required check with paths
  .github/workflows/eslint.yml
Labels: merge

#883 Apply nav menu classes only if `theme_location` parameter is populated
  changelog.md
  wp-content/plugins/core/src/Nav_Menus/Nav_Attribute_Filters.php
Labels: enhance

#890 Improves and fixes automated script preloading
  changelog.md
  wp-content/plugins/core/src/Assets/Theme/Scripts.php
Labels: bug
