Repository moderntribe/square-one, pull requests merged in 2021-05, with the labels that each got.

#705 Add phpcs Installation Documentation
  changelog.md
  docs/getting-started/phpcs.md
Labels: documentation

#704 Reorganization of Docs
  docs/basics/cli.md
  docs/basics/components.md
  docs/basics/database.md
  docs/basics/forms.md
  docs/basics/object-cache.md
  docs/basics/p2p.md
  docs/basics/settings.md
  docs/basics/taxonomies.md
  docs/basics/templates.md
  docs/basics/theme-assets.md
  docs/concepts/container.md
  docs/concepts/subscribers.md
  docs/getting-started/01 installation.md
  docs/getting-started/02 local-env.md
  docs/getting-started/03 build.md
  docs/getting-started/04 configuration.md
  docs/getting-started/05 structure.md
  docs/getting-started/06 deployment.md
  docs/tooling/build-system.md
  docs/tooling/docker.md
Labels: documentation

#729 Update WPLCI to 2.5.0. Also general composer.lock update for all depe…
  composer.json
  composer.lock
Labels: security

#730 add dependabot dependencies management to SQ1.
  .github/dependabot.yml
  composer.json
  composer.lock
Labels: code review
