Repository moderntribe/square-one, pull requests merged in 2021-06, with the labels that each got.

#740 [SQONE-605] Minimal MCE toolbar (default for all custom blocks)
  wp-content/plugins/core/src/Admin/Admin_Subscriber.php
  wp-content/plugins/core/src/Admin/Editor/Classic_Editor_Formats.php
  wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion.php
  wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Content_Columns/Content_Columns.php
  wp-content/plugins/core/src/Blocks/Types/Content_Loop/Content_Loop.php
  wp-content/plugins/core/src/Blocks/Types/Gallery_Grid/Gallery_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Hero/Hero.php
  wp-content/plugins/core/src/Blocks/Types/Icon_Grid/Icon_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Lead_Form/Lead_Form.php
  wp-content/plugins/core/src/Blocks/Types/Links/Links.php
  wp-content/plugins/core/src/Blocks/Types/Logos/Logos.php
  wp-content/plugins/core/src/Blocks/Types/Media_Text/Media_Text.php
  wp-content/plugins/core/src/Blocks/Types/Stats/Stats.php
  wp-content/plugins/core/src/Blocks/Types/Tabs/Tabs.php
Labels: Pending QA

#771 Update VS Code PHPCS Documentation
  docs/tooling/phpcs.md
Labels: documentation

#769 [SQONE-619] Update Interstitial Block Fields
  wp-content/plugins/core/src/Blocks/Types/Interstitial/Interstitial.php
  wp-content/plugins/core/src/Blocks/Types/Interstitial/Interstitial_Model.php
  wp-content/themes/core/components/blocks/interstitial/Interstitial_Block_Controller.php
Labels: merge

#770 [SQONE-616] Update Quote Block Fields
  wp-content/plugins/core/src/Blocks/Types/Quote/Quote.php
  wp-content/plugins/core/src/Blocks/Types/Quote/Quote_Model.php
Labels: merge

#780 [SQONE-618] Update Hero Block Fields
  wp-content/plugins/core/src/Blocks/Types/Hero/Hero.php
Labels: merge

#767 [SQONE-613] Update Tab Block Fields
  wp-content/plugins/core/src/Blocks/Types/Tabs/Tabs.php
Labels: merge

#753 Updates the button block field type
  changelog.md
  wp-content/plugins/core/src/Blocks/Types/Buttons/Buttons.php
Labels: merge

#776 Add PHP Storm phpcs instructions
  docs/tooling/img/phpstorm-setup-1.png
  docs/tooling/img/phpstorm-setup-2.png
  docs/tooling/img/phpstorm-setup-3.png
  docs/tooling/img/phpstorm-setup-4.png
  docs/tooling/phpcs.md
Labels: merge

#789 Bug/links block rendering
  wp-content/themes/core/components/blocks/links/Links_Block_Controller.php
  wp-content/themes/core/components/blocks/links/css/links.pcss
  wp-content/themes/core/components/blocks/links/links.php
  wp-content/themes/core/components/link/Link_Controller.php
Labels: Pending QA

#781 [SQONE-614] Update Media Text Block Fields
  wp-content/plugins/core/src/Blocks/Types/Media_Text/Media_Text.php
Labels: Pending QA

#782 [SQONE-615] Update Lead Form Block Fields
  wp-content/plugins/core/src/Blocks/Types/Lead_Form/Lead_Form.php
Labels: Pending QA

#713 Feature/sqone 273/basic page template
  wp-content/plugins/core/src/Theme/Pagination_Util.php
  wp-content/themes/core/assets/css/src/_mixins.pcss
  wp-content/themes/core/assets/css/src/theme/media/_mixins.pcss
  wp-content/themes/core/assets/css/src/theme/separators/_utilities.pcss
  wp-content/themes/core/components/breadcrumbs/css/breadcrumbs.pcss
  wp-content/themes/core/components/header/subheader/Subheader_Controller.php
  wp-content/themes/core/components/header/subheader/css/subheader.pcss
  wp-content/themes/core/components/header/subheader/index.pcss
  wp-content/themes/core/components/header/subheader/subheader.php
  wp-content/themes/core/components/image/css/image.pcss
  wp-content/themes/core/components/routes/page/Page_Controller.php
  wp-content/themes/core/components/routes/page/page.php
Labels: Pending QA
