Repository moderntribe/square-one, pull requests merged in 2022-07, with the labels that each got.

#1002 Add User Input Content to Security Docs
  docs/concepts/security.md
Labels: documentation

#1015 [SQONE-691]: Buttons Block Updates
  changelog.md
  wp-content/themes/core/components/blocks/buttons/buttons.php
  wp-content/themes/core/components/blocks/buttons/css/buttons.pcss
Labels: code review, Launch Environment

#930 Add optimized opcache configuration
  dev/docker/php/php-ini-overrides.ini
Labels: Needs Developer Testing, Needs Changelog Entry

#1013 Feature/sqone 270/site footer
  changelog.md
  gulp-tasks/cssnano.js
  gulp-tasks/header.js
  gulp-tasks/postcss.js
  gulp-tasks/stylelint.js
  gulp-tasks/watch.js
  gulpfile.js
  webpack.config.js
  wp-content/plugins/core/src/Assets/Assets_Subscriber.php
  wp-content/plugins/core/src/Assets/Theme/Legacy_Check.php
  wp-content/plugins/core/src/Assets/Theme/Styles.php
  wp-content/plugins/core/src/Assets/Theme/Theme_Build_Parser.php
  wp-content/plugins/core/src/Theme/Config/Web_Fonts.php
  wp-content/plugins/core/src/Theme/Theme_Subscriber.php
  wp-content/themes/core/assets/css/src/theme/legacy.pcss
  wp-content/themes/core/assets/img/theme/legacy-browser/chrome.svg
  wp-content/themes/core/assets/img/theme/legacy-browser/edge.svg
  wp-content/themes/core/assets/img/theme/legacy-browser/firefox.svg
  wp-content/themes/core/assets/img/theme/legacy-browser/safari.svg
  wp-content/themes/core/routes/unsupported_browser/Unsupported_Browser_Controller.php
  wp-content/themes/core/routes/unsupported_browser/css/_variables.pcss
  wp-content/themes/core/routes/unsupported_browser/css/unsupported-browser.pcss
  wp-content/themes/core/routes/unsupported_browser/unsupported_browser.php
Labels: Launch Environment

#1011 Field Name and Icon Consistency
  changelog.md
  wp-content/plugins/core/src/Blocks/Block_Category.php
  wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
  wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion.php
  wp-content/plugins/core/src/Blocks/Types/Buttons/Buttons.php
  wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Content_Columns/Content_Columns.php
  wp-content/plugins/core/src/Blocks/Types/Content_Loop/Content_Loop.php
  wp-content/plugins/core/src/Blocks/Types/Gallery_Grid/Gallery_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Gallery_Slider/Gallery_Slider.php
  wp-content/plugins/core/src/Blocks/Types/Hero/Hero.php
  wp-content/plugins/core/src/Blocks/Types/Icon_Grid/Icon_Grid.php
  wp-content/plugins/core/src/Blocks/Types/Interstitial/Interstitial.php
  wp-content/plugins/core/src/Blocks/Types/Lead_Form/Lead_Form.php
  wp-content/plugins/core/src/Blocks/Types/Links/Links.php
  wp-content/plugins/core/src/Blocks/Types/Logos/Logos.php
  wp-content/plugins/core/src/Blocks/Types/Media_Text/Media_Text.php
  wp-content/plugins/core/src/Blocks/Types/Quote/Quote.php
  wp-content/plugins/core/src/Blocks/Types/Section_Nav/Section_Nav.php
  wp-content/plugins/core/src/Blocks/Types/Spacer/Spacer.php
  wp-content/plugins/core/src/Blocks/Types/Stats/Stats.php
  wp-content/plugins/core/src/Blocks/Types/Tabs/Tabs.php
  wp-content/themes/core/assets/img/admin/blocks/accordion/inline.svg
  wp-content/themes/core/assets/img/admin/blocks/accordion/stacked.svg
  wp-content/themes/core/assets/img/admin/blocks/cardgrid/inline.svg
  wp-content/themes/core/assets/img/admin/blocks/cardgrid/stacked.svg
  wp-content/themes/core/assets/img/admin/blocks/contentcolumns/center.svg
  wp-content/themes/core/assets/img/admin/blocks/contentcolumns/left.svg
  wp-content/themes/core/assets/img/admin/blocks/contentloop/layout_columns.svg
  wp-content/themes/core/assets/img/admin/blocks/contentloop/layout_feature.svg
  wp-content/themes/core/assets/img/admin/blocks/contentloop/layout_row.svg
  wp-content/themes/core/assets/img/admin/blocks/hero/center.svg
  wp-content/themes/core/assets/img/admin/blocks/hero/left.svg
  wp-content/themes/core/assets/img/admin/blocks/interstitial/center.svg
  wp-content/themes/core/assets/img/admin/blocks/interstitial/left.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/bottom.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/center.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/form_inline.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/form_stacked.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/left.svg
  wp-content/themes/core/assets/img/admin/blocks/leadform/right.svg
  wp-content/themes/core/assets/img/admin/blocks/links/inline.svg
  wp-content/themes/core/assets/img/admin/blocks/links/stacked.svg
  wp-content/themes/core/assets/img/admin/blocks/mediatext/center.svg
  wp-content/themes/core/assets/img/admin/blocks/mediatext/full.svg
  wp-content/themes/core/assets/img/admin/blocks/mediatext/grid.svg
  wp-content/themes/core/assets/img/admin/blocks/mediatext/left.svg
  wp-content/themes/core/assets/img/admin/blocks/mediatext/right.svg
  wp-content/themes/core/assets/img/admin/blocks/quote/left.svg
  wp-content/themes/core/assets/img/admin/blocks/quote/overlay.svg
  wp-content/themes/core/assets/img/admin/blocks/quote/right.svg
  wp-content/themes/core/assets/img/admin/blocks/stats/center.svg
  wp-content/themes/core/assets/img/admin/blocks/stats/inline.svg
  wp-content/themes/core/assets/img/admin/blocks/stats/left.svg
  wp-content/themes/core/assets/img/admin/blocks/stats/stacked.svg
  wp-content/themes/core/assets/img/admin/blocks/tabs/horizontal.svg
  wp-content/themes/core/assets/img/admin/blocks/tabs/vertical.svg
Labels: Launch Environment
